//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs_CC/3D/3D_Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @_3D_Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @_3D_Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""3D_Controls"",
    ""maps"": [
        {
            ""name"": ""Isometric_Ish"",
            ""id"": ""32f130a2-9fb9-49ca-9aa8-db7b686aca02"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""4064490a-a652-4cfb-beb5-9c2b3b4e922a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""26c5f5f0-2fad-49a3-bb9a-33c3393c9756"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b9953fd8-ddf3-4542-ba80-10e3acdc424e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""113ff151-0eb1-4963-bd6e-6813930bf203"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FSM"",
            ""id"": ""244644fd-3567-4d49-9871-ebeb5fddf8a9"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d9ac847e-32b0-49c5-8b02-cdcf76e33f72"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""f0dac57f-cb1a-4e54-83d1-a1c4799d6d21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""3a6dc69c-b992-4f7e-870b-9f29559277da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Special1"",
                    ""type"": ""Button"",
                    ""id"": ""1a5ab1a6-26cc-4f93-9645-356b4e868af0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Special2"",
                    ""type"": ""Button"",
                    ""id"": ""21200ab6-c585-43fd-84e4-5777e22ed872"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""40d22763-9663-4910-b9de-77990fdcc10c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d07d51d5-dfb9-4cb2-8e6c-bc80f860d9d9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ff166246-0ef2-4d51-89c0-db64d677a863"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f68266a7-36f4-4bcf-8b4e-6d8eb0a3ad02"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1a686c67-cd18-4d4f-b282-e326a7f6cb5f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""93595df2-554b-47a6-9117-381e27364e3e"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0124ad2f-6669-4fe5-9dcb-f497b7dbba38"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""687d3d6c-458a-4ef9-a9ee-50619de364fc"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9150cde1-e0f9-43a0-b905-ea023b369a9f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Special2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MouseLook"",
            ""id"": ""ccef0f3d-1a09-4285-906f-2f90ac8687ed"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c0bf3556-f63f-4824-b211-cd9c01c95520"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d0146090-6113-434a-8b43-1bc921624650"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Other"",
            ""id"": ""073b9fff-17bd-4b03-b718-36494a56a4d4"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c797b3bb-5b85-4a4a-9c1f-a4384d32a54c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""710d3e77-50c6-432e-ae6b-550dadc57ad5"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b802472-823d-467c-b9f3-fc2fd98fe0d5"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Isometric_Ish
        m_Isometric_Ish = asset.FindActionMap("Isometric_Ish", throwIfNotFound: true);
        m_Isometric_Ish_Click = m_Isometric_Ish.FindAction("Click", throwIfNotFound: true);
        m_Isometric_Ish_MousePosition = m_Isometric_Ish.FindAction("MousePosition", throwIfNotFound: true);
        // FSM
        m_FSM = asset.FindActionMap("FSM", throwIfNotFound: true);
        m_FSM_Move = m_FSM.FindAction("Move", throwIfNotFound: true);
        m_FSM_Sprint = m_FSM.FindAction("Sprint", throwIfNotFound: true);
        m_FSM_Interact = m_FSM.FindAction("Interact", throwIfNotFound: true);
        m_FSM_Special1 = m_FSM.FindAction("Special1", throwIfNotFound: true);
        m_FSM_Special2 = m_FSM.FindAction("Special2", throwIfNotFound: true);
        // MouseLook
        m_MouseLook = asset.FindActionMap("MouseLook", throwIfNotFound: true);
        m_MouseLook_Look = m_MouseLook.FindAction("Look", throwIfNotFound: true);
        // Other
        m_Other = asset.FindActionMap("Other", throwIfNotFound: true);
        m_Other_Pause = m_Other.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Isometric_Ish
    private readonly InputActionMap m_Isometric_Ish;
    private List<IIsometric_IshActions> m_Isometric_IshActionsCallbackInterfaces = new List<IIsometric_IshActions>();
    private readonly InputAction m_Isometric_Ish_Click;
    private readonly InputAction m_Isometric_Ish_MousePosition;
    public struct Isometric_IshActions
    {
        private @_3D_Controls m_Wrapper;
        public Isometric_IshActions(@_3D_Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_Isometric_Ish_Click;
        public InputAction @MousePosition => m_Wrapper.m_Isometric_Ish_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_Isometric_Ish; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Isometric_IshActions set) { return set.Get(); }
        public void AddCallbacks(IIsometric_IshActions instance)
        {
            if (instance == null || m_Wrapper.m_Isometric_IshActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Isometric_IshActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IIsometric_IshActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IIsometric_IshActions instance)
        {
            if (m_Wrapper.m_Isometric_IshActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IIsometric_IshActions instance)
        {
            foreach (var item in m_Wrapper.m_Isometric_IshActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Isometric_IshActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Isometric_IshActions @Isometric_Ish => new Isometric_IshActions(this);

    // FSM
    private readonly InputActionMap m_FSM;
    private List<IFSMActions> m_FSMActionsCallbackInterfaces = new List<IFSMActions>();
    private readonly InputAction m_FSM_Move;
    private readonly InputAction m_FSM_Sprint;
    private readonly InputAction m_FSM_Interact;
    private readonly InputAction m_FSM_Special1;
    private readonly InputAction m_FSM_Special2;
    public struct FSMActions
    {
        private @_3D_Controls m_Wrapper;
        public FSMActions(@_3D_Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_FSM_Move;
        public InputAction @Sprint => m_Wrapper.m_FSM_Sprint;
        public InputAction @Interact => m_Wrapper.m_FSM_Interact;
        public InputAction @Special1 => m_Wrapper.m_FSM_Special1;
        public InputAction @Special2 => m_Wrapper.m_FSM_Special2;
        public InputActionMap Get() { return m_Wrapper.m_FSM; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FSMActions set) { return set.Get(); }
        public void AddCallbacks(IFSMActions instance)
        {
            if (instance == null || m_Wrapper.m_FSMActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FSMActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Special1.started += instance.OnSpecial1;
            @Special1.performed += instance.OnSpecial1;
            @Special1.canceled += instance.OnSpecial1;
            @Special2.started += instance.OnSpecial2;
            @Special2.performed += instance.OnSpecial2;
            @Special2.canceled += instance.OnSpecial2;
        }

        private void UnregisterCallbacks(IFSMActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Special1.started -= instance.OnSpecial1;
            @Special1.performed -= instance.OnSpecial1;
            @Special1.canceled -= instance.OnSpecial1;
            @Special2.started -= instance.OnSpecial2;
            @Special2.performed -= instance.OnSpecial2;
            @Special2.canceled -= instance.OnSpecial2;
        }

        public void RemoveCallbacks(IFSMActions instance)
        {
            if (m_Wrapper.m_FSMActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFSMActions instance)
        {
            foreach (var item in m_Wrapper.m_FSMActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FSMActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FSMActions @FSM => new FSMActions(this);

    // MouseLook
    private readonly InputActionMap m_MouseLook;
    private List<IMouseLookActions> m_MouseLookActionsCallbackInterfaces = new List<IMouseLookActions>();
    private readonly InputAction m_MouseLook_Look;
    public struct MouseLookActions
    {
        private @_3D_Controls m_Wrapper;
        public MouseLookActions(@_3D_Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_MouseLook_Look;
        public InputActionMap Get() { return m_Wrapper.m_MouseLook; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseLookActions set) { return set.Get(); }
        public void AddCallbacks(IMouseLookActions instance)
        {
            if (instance == null || m_Wrapper.m_MouseLookActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MouseLookActionsCallbackInterfaces.Add(instance);
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(IMouseLookActions instance)
        {
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(IMouseLookActions instance)
        {
            if (m_Wrapper.m_MouseLookActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMouseLookActions instance)
        {
            foreach (var item in m_Wrapper.m_MouseLookActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MouseLookActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MouseLookActions @MouseLook => new MouseLookActions(this);

    // Other
    private readonly InputActionMap m_Other;
    private List<IOtherActions> m_OtherActionsCallbackInterfaces = new List<IOtherActions>();
    private readonly InputAction m_Other_Pause;
    public struct OtherActions
    {
        private @_3D_Controls m_Wrapper;
        public OtherActions(@_3D_Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_Other_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Other; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OtherActions set) { return set.Get(); }
        public void AddCallbacks(IOtherActions instance)
        {
            if (instance == null || m_Wrapper.m_OtherActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OtherActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IOtherActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IOtherActions instance)
        {
            if (m_Wrapper.m_OtherActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOtherActions instance)
        {
            foreach (var item in m_Wrapper.m_OtherActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OtherActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OtherActions @Other => new OtherActions(this);
    public interface IIsometric_IshActions
    {
        void OnClick(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
    public interface IFSMActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnSpecial1(InputAction.CallbackContext context);
        void OnSpecial2(InputAction.CallbackContext context);
    }
    public interface IMouseLookActions
    {
        void OnLook(InputAction.CallbackContext context);
    }
    public interface IOtherActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
